import pandas as pd

mean_land_size_df_dict = {
    0: pd.read_csv('schema/preprocess/data/table/hcm_mean_land_size_df.csv'),
    1: pd.read_csv('schema/preprocess/data/table/hn_mean_land_size_df.csv')
}

rename_dict = {'numberOfFloors': 'numberOfFloors',
 'numberOfBathRooms': 'numberOfBathRooms',
 'numberOfLivingRooms': 'numberOfBedRooms',
 'certificateOfLandUseRight': 'certificateOfLandUseRight',
 'ward': 'ward',
 'street': 'street',
 'district': 'district',
 'city': 'city',
 'lat': 'lat',
 'lon': 'lon',
 'typeOfRealEstate': 'typeOfRealEstate',
 'frontWidth': 'frontWidth',
 'endWidth': 'endWidth',
 'facade': 'facade',
 'houseDirection': 'houseDirection',
 'landSize': 'landSize',
 'accessibility': 'accessibility',
 'time': 'time',
 'w': 'w',
 'h': 'h',
 'num_of_university_in_500m_radius': 'num_of_university_in_500m_radius',
 'num_of_fuel_in_500m_radius': 'num_of_fuel_in_500m_radius',
 'num_of_cafe_in_500m_radius': 'num_of_cafe_in_500m_radius',
 'num_of_parking_in_500m_radius': 'num_of_parking_in_500m_radius',
 'num_of_parking_entrance_in_500m_radius': 'num_of_parking_entrance_in_500m_radius',
 'num_of_fast_food_in_500m_radius': 'num_of_fast_food_in_500m_radius',
 'num_of_marketplace_in_500m_radius': 'num_of_marketplace_in_500m_radius',
 'num_of_restaurant_in_500m_radius': 'num_of_restaurant_in_500m_radius',
 'num_of_hospital_in_500m_radius': 'num_of_hospital_in_500m_radius',
 'num_of_school_in_500m_radius': 'num_of_school_in_500m_radius',
 'num_of_kindergarten_in_500m_radius': 'num_of_kindergarten_in_500m_radius',
 'num_of_townhall - community_centre_in_500m_radius': 'num_of_townhallcommunity_centre_in_500m_radius',
 'num_of_police_in_500m_radius': 'num_of_police_in_500m_radius',
 'num_of_place_of_worship_in_500m_radius': 'num_of_place_of_worship_in_500m_radius',
 'num_of_bank_in_500m_radius': 'num_of_bank_in_500m_radius',
 'num_of_atm_in_500m_radius': 'num_of_atm_in_500m_radius',
 'num_of_university_in_1000m_radius': 'num_of_university_in_1000m_radius',
 'num_of_fuel_in_1000m_radius': 'num_of_fuel_in_1000m_radius',
 'num_of_cafe_in_1000m_radius': 'num_of_cafe_in_1000m_radius',
 'num_of_parking_in_1000m_radius': 'num_of_parking_in_1000m_radius',
 'num_of_parking_entrance_in_1000m_radius': 'num_of_parking_entrance_in_1000m_radius',
 'num_of_fast_food_in_1000m_radius': 'num_of_fast_food_in_1000m_radius',
 'num_of_marketplace_in_1000m_radius': 'num_of_marketplace_in_1000m_radius',
 'num_of_restaurant_in_1000m_radius': 'num_of_restaurant_in_1000m_radius',
 'num_of_hospital_in_1000m_radius': 'num_of_hospital_in_1000m_radius',
 'num_of_school_in_1000m_radius': 'num_of_school_in_1000m_radius',
 'num_of_kindergarten_in_1000m_radius': 'num_of_kindergarten_in_1000m_radius',
 'num_of_townhall - community_centre_in_1000m_radius': 'num_of_townhallcommunity_centre_in_1000m_radius',
 'num_of_police_in_1000m_radius': 'num_of_police_in_1000m_radius',
 'num_of_place_of_worship_in_1000m_radius': 'num_of_place_of_worship_in_1000m_radius',
 'num_of_bank_in_1000m_radius': 'num_of_bank_in_1000m_radius',
 'num_of_atm_in_1000m_radius': 'num_of_atm_in_1000m_radius',
 'num_of_university_in_2000m_radius': 'num_of_university_in_2000m_radius',
 'num_of_fuel_in_2000m_radius': 'num_of_fuel_in_2000m_radius',
 'num_of_cafe_in_2000m_radius': 'num_of_cafe_in_2000m_radius',
 'num_of_parking_in_2000m_radius': 'num_of_parking_in_2000m_radius',
 'num_of_parking_entrance_in_2000m_radius': 'num_of_parking_entrance_in_2000m_radius',
 'num_of_fast_food_in_2000m_radius': 'num_of_fast_food_in_2000m_radius',
 'num_of_marketplace_in_2000m_radius': 'num_of_marketplace_in_2000m_radius',
 'num_of_restaurant_in_2000m_radius': 'num_of_restaurant_in_2000m_radius',
 'num_of_hospital_in_2000m_radius': 'num_of_hospital_in_2000m_radius',
 'num_of_school_in_2000m_radius': 'num_of_school_in_2000m_radius',
 'num_of_kindergarten_in_2000m_radius': 'num_of_kindergarten_in_2000m_radius',
 'num_of_townhall - community_centre_in_2000m_radius': 'num_of_townhallcommunity_centre_in_2000m_radius',
 'num_of_police_in_2000m_radius': 'num_of_police_in_2000m_radius',
 'num_of_place_of_worship_in_2000m_radius': 'num_of_place_of_worship_in_2000m_radius',
 'num_of_bank_in_2000m_radius': 'num_of_bank_in_2000m_radius',
 'num_of_atm_in_2000m_radius': 'num_of_atm_in_2000m_radius',
 'administrative_genre': 'administrative_genre',
 'acreage': 'acreage',
 'population': 'population',
 'density': 'density',
 'district_lat': 'district_lat',
 'district_lon': 'district_lon',
 'num_of_ward': 'num_of_ward',
 'distance_hn_TTTM Saigon Centre (Takashimaya)': 'distance_hn_TTTMSaigonCentreTakashimaya',
 'distance_hn_Crescent Mall': 'distance_hn_CrescentMall',
 'distance_hn_SC VivoCity Shopping Center': 'distance_hn_SCVivoCityShoppingCenter',
 'distance_hn_Aeon Mall Shopping Center Tân Phú': 'distance_hn_AeonMallShoppingCenterTanPhu',
 'distance_hn_Saigon Garden': 'distance_hn_SaigonGarden',
 'distance_hn_Vincom Đồng Khởi': 'distance_hn_VincomDongKhoi',
 'distance_hn_Diamond Plaza Shopping Center': 'distance_hn_DiamondPlazaShoppingCenter',
 'distance_hn_Công viên Vinhomes Central Park': 'distance_hn_CongvienVinhomesCentralPark',
 'distance_hn_Công viên khu đô thị Sala': 'distance_hn_CongvienkhudothiSala',
 'distance_hn_Công viên trên mây tại Taka Shimaya': 'distance_hn_CongvientrenmaytaiTakaShimaya',
 'distance_hn_Công viên cá Koi Rin Rin Park': 'distance_hn_CongviencaKoiRinRinPark',
 'distance_hn_Công viên cầu Ánh Sao – Hồ Bán Nguyệt': 'distance_hn_CongviencauAnhSaoHoBanNguyet',
 'distance_hn_Công viên Thỏ Trắng': 'distance_hn_CongvienThoTrang',
 'distance_hn_Thảo Cầm Viên': 'distance_hn_ThaoCamVien',
 'distance_hn_Công viên Tao Đàn': 'distance_hn_CongvienTaoDan',
 'distance_hn_Công viên Lê Văn Tám': 'distance_hn_CongvienLeVanTam',
 'distance_hn_Công viên 30-4': 'distance_hn_Congvien304',
 'distance_hn_Công viên nước Đầm Sen': 'distance_hn_CongviennuocDamSen',
 'distance_hn_Công viên phép thuật Harry Potter': 'distance_hn_CongvienphepthuatHarryPotter',
 'distance_hn_Công viên Gia Định': 'distance_hn_CongvienGiaDinh',
 'distance_hn_Công viên 23-9': 'distance_hn_Congvien239',
 'distance_hn_Công viên nước Củ Chi': 'distance_hn_CongviennuocCuChi',
 'distance_hn_Công viên Hoàng Văn Thụ': 'distance_hn_CongvienHoangVanThu',
 'distance_hn_Đường Nguyễn Huệ, quận 1, TPHCM': 'distance_hn_DuongNguyenHuequan1TPHCM',
 'distance_hn_Đường Lê Lợi, quận 1, TPHCM': 'distance_hn_DuongLeLoiquan1TPHCM',
 'distance_hn_Đường Đồng Khởi, quận 1, TPHCM': 'distance_hn_DuongDongKhoiquan1TPHCM',
 'distance_hn_Đường Lê Anh Xuân, quận 1': 'distance_hn_DuongLeAnhXuanquan1',
 'distance_hn_Đường Lê Duẩn': 'distance_hn_DuongLeDuan',
 'distance_hn_Đường Mạc Thị Bưởi': 'distance_hn_DuongMacThiBuoi',
 'distance_hn_Công trường Lam Sơn': 'distance_hn_CongtruongLamSon',
 'distance_hn_Đường Nam Kỳ Khởi Nghĩa': 'distance_hn_DuongNamKyKhoiNghia',
 'distance_hn_Đường Mai Chí Thọ': 'distance_hn_DuongMaiChiTho',
 'distance_hn_Đường Nguyễn Thị Định': 'distance_hn_DuongNguyenThiDinh',
 'distance_hn_Đường Võ Chí Công': 'distance_hn_DuongVoChiCong',
 'distance_hn_Đường Hai Bà Trưng': 'distance_hn_DuongHaiBaTrung',
 'distance_hn_Nguyễn Thị Minh Khai': 'distance_hn_NguyenThiMinhKhai',
 'distance_hn_Lê Văn Sỹ': 'distance_hn_LeVanSy',
 'distance_hn_Bà Huyện Thanh Quan': 'distance_hn_BaHuyenThanhQuan',
 'distance_hn_Đường Nguyễn Tất Thành': 'distance_hn_DuongNguyenTatThanh',
 'distance_hn_Bến Vân Đồn': 'distance_hn_BenVanDon',
 'distance_hn_Tôn Thất Thuyết': 'distance_hn_TonThatThuyet',
 'distance_hn_Đoàn Văn Bơ': 'distance_hn_DoanVanBo',
 'distance_hn_Nguyễn Tri Phương': 'distance_hn_NguyenTriPhuong',
 'distance_hn_Hùng Vương': 'distance_hn_HungVuong',
 'distance_hn_Lê Hồng Phong': 'distance_hn_LeHongPhong',
 'distance_hn_Trần Hưng Đạo': 'distance_hn_TranHungDao',
 'distance_hn_Hậu Giang': 'distance_hn_HauGiang',
 'distance_hn_Nguyễn Văn Luông': 'distance_hn_NguyenVanLuong',
 'distance_hn_Kinh Dương Vương': 'distance_hn_KinhDuongVuong',
 'distance_hn_Nguyễn Văn Linh': 'distance_hn_NguyenVanLinh',
 'distance_hn_Đào Trí': 'distance_hn_DaoTri',
 'distance_hn_Nguyễn Thị Thập': 'distance_hn_NguyenThiThap',
 'distance_hcm_Vincom Times City': 'distance_hcm_VincomTimesCity',
 'distance_hcm_Lotte Center Hanoi': 'distance_hcm_LotteCenterHanoi',
 'distance_hcm_Aeon Mall Hà Đông': 'distance_hcm_AeonMallHaDong',
 'distance_hcm_Trung tâm thương mại Royal City Hà Nội': 'distance_hcm_TrungtamthuongmaiRoyalCityHaNoi',
 'distance_hcm_Indochina Plaza Hanoi Residences': 'distance_hcm_IndochinaPlazaHanoiResidences',
 'distance_hcm_Trung tâm thương mại Hà Nội Aqua Central': 'distance_hcm_TrungtamthuongmaiHaNoiAquaCentral',
 'distance_hcm_Trung tâm thương mại Hà Nội Center Point': 'distance_hcm_TrungtamthuongmaiHaNoiCenterPoint',
 'distance_hcm_Trung tâm thương mại Hà Nội Tràng Tiền Plaza ': 'distance_hcm_TrungtamthuongmaiHaNoiTrangTienPlaza',
 'distance_hcm_Trung tâm thương mại Hà Nội Keangnam': 'distance_hcm_TrungtamthuongmaiHaNoiKeangnam',
 'distance_hcm_Aeon Mall Long Biên': 'distance_hcm_AeonMallLongBien',
 'distance_hcm_Vincom Bà Triệu': 'distance_hcm_VincomBaTrieu',
 'distance_hcm_GO! Thăng Long': 'distance_hcm_GOThangLong',
 'distance_hcm_Tops Market The Garden': 'distance_hcm_TopsMarketTheGarden',
 'distance_hcm_WinMart': 'distance_hcm_WinMart',
 'distance_hcm_Tops Market Lê Trọng Tấn': 'distance_hcm_TopsMarketLeTrongTan',
 'distance_hcm_Lotte Mart Đống Đa': 'distance_hcm_LotteMartDongDa',
 'distance_hcm_Lotte Mart Cầu Giấy': 'distance_hcm_LotteMartCauGiay',
 'distance_hcm_Công viên yên sở': 'distance_hcm_Congvienyenso',
 'distance_hcm_Công viên thống nhất': 'distance_hcm_Congvienthongnhat',
 'distance_hcm_Công viên thủ lệ': 'distance_hcm_Congvienthule',
 'distance_hcm_Công viên hòa bình': 'distance_hcm_Congvienhoabinh',
 'distance_hcm_Công viên nước Hồ Tây': 'distance_hcm_CongviennuocHoTay',
 'distance_hcm_Công Viên Thiên Đường Bảo Sơn': 'distance_hcm_CongVienThienDuongBaoSon',
 'distance_hcm_Công viên Nghĩa Đô': 'distance_hcm_CongvienNghiaDo',
 'distance_hcm_Vườn hoa Lý Thái Tổ': 'distance_hcm_VuonhoaLyThaiTo',
 'distance_hcm_Vườn hoa Lênin': 'distance_hcm_VuonhoaLenin',
 'distance_hcm_Công viên Văn hóa Đống Đa': 'distance_hcm_CongvienVanhoaDongDa',
 'distance_hcm_Vườn Hoa Pasteur': 'distance_hcm_VuonHoaPasteur',
 'distance_hcm_Hồ Ngọc Khánh': 'distance_hcm_HoNgocKhanh',
 'distance_hcm_Hồ Gươm': 'distance_hcm_HoGuom',
 'distance_hcm_Hồ Tây 1': 'distance_hcm_HoTay1',
 'distance_hcm_Hồ Tây 2': 'distance_hcm_HoTay2',
 'distance_hcm_Hồ Tây 3': 'distance_hcm_HoTay3',
 'distance_hcm_Hồ Tây 4': 'distance_hcm_HoTay4',
 'distance_hcm_Hồ Tây 5': 'distance_hcm_HoTay5',
 'distance_hcm_Hồ Tây 6': 'distance_hcm_HoTay6',
 'distance_hcm_Hồ Tây 7': 'distance_hcm_HoTay7',
 'distance_hcm_Hồ Tây 8': 'distance_hcm_HoTay8',
 'distance_hcm_Phố Lê Thái Tổ': 'distance_hcm_PhoLeThaiTo',
 'distance_hcm_Phố Bảo Khánh': 'distance_hcm_PhoBaoKhanh',
 'distance_hcm_Phố Hàng Đào': 'distance_hcm_PhoHangDao',
 'distance_hcm_Hàng Khay': 'distance_hcm_HangKhay',
 'distance_hcm_Hàng Trống': 'distance_hcm_HangTrong',
 'distance_hcm_Hàng Hành': 'distance_hcm_HangHanh',
 'distance_hcm_Phố Hai Bà Trưng': 'distance_hcm_PhoHaiBaTrung',
 'distance_hcm_Phố Lý Thường Kiệt': 'distance_hcm_PhoLyThuongKiet',
 'distance_hcm_Phố Bà Triệu': 'distance_hcm_PhoBaTrieu',
 'distance_hcm_Hàng Bài': 'distance_hcm_HangBai',
 'distance_hcm_Phố Hai Bà Trưng(Hoàn Kiếm)': 'distance_hcm_PhoHaiBaTrungHoanKiem',
 'distance_district': 'distance_district',
 'nearest_0_lat': 'nearest_0_lat',
 'nearest_0_lon': 'nearest_0_lon',
 'nearest_0_district': 'nearest_0_district',
 'nearest_0_street': 'nearest_0_street',
 'nearest_0_ward': 'nearest_0_ward',
 'nearest_1_lat': 'nearest_1_lat',
 'nearest_1_lon': 'nearest_1_lon',
 'nearest_1_district': 'nearest_1_district',
 'nearest_1_street': 'nearest_1_street',
 'nearest_1_ward': 'nearest_1_ward',
 'nearest_2_lat': 'nearest_2_lat',
 'nearest_2_lon': 'nearest_2_lon',
 'nearest_2_district': 'nearest_2_district',
 'nearest_2_street': 'nearest_2_street',
 'nearest_2_ward': 'nearest_2_ward',
 'nearest_3_lat': 'nearest_3_lat',
 'nearest_3_lon': 'nearest_3_lon',
 'nearest_3_district': 'nearest_3_district',
 'nearest_3_street': 'nearest_3_street',
 'nearest_3_ward': 'nearest_3_ward',
 'nearest_4_lat': 'nearest_4_lat',
 'nearest_4_lon': 'nearest_4_lon',
 'nearest_4_district': 'nearest_4_district',
 'nearest_4_street': 'nearest_4_street',
 'nearest_4_ward': 'nearest_4_ward',
 'nearest_5_lat': 'nearest_5_lat',
 'nearest_5_lon': 'nearest_5_lon',
 'nearest_5_district': 'nearest_5_district',
 'nearest_5_street': 'nearest_5_street',
 'nearest_5_ward': 'nearest_5_ward',
 'nearest_6_lat': 'nearest_6_lat',
 'nearest_6_lon': 'nearest_6_lon',
 'nearest_6_district': 'nearest_6_district',
 'nearest_6_street': 'nearest_6_street',
 'nearest_6_ward': 'nearest_6_ward',
 'nearest_7_lat': 'nearest_7_lat',
 'nearest_7_lon': 'nearest_7_lon',
 'nearest_7_district': 'nearest_7_district',
 'nearest_7_street': 'nearest_7_street',
 'nearest_7_ward': 'nearest_7_ward',
 'nearest_8_lat': 'nearest_8_lat',
 'nearest_8_lon': 'nearest_8_lon',
 'nearest_8_district': 'nearest_8_district',
 'nearest_8_street': 'nearest_8_street',
 'nearest_8_ward': 'nearest_8_ward',
 'distance_nearest_0': 'distance_nearest_0',
 'distance_nearest_1': 'distance_nearest_1',
 'distance_nearest_2': 'distance_nearest_2',
 'distance_nearest_3': 'distance_nearest_3',
 'distance_nearest_4': 'distance_nearest_4',
 'distance_nearest_5': 'distance_nearest_5',
 'distance_nearest_6': 'distance_nearest_6',
 'distance_nearest_7': 'distance_nearest_7',
 'distance_nearest_8': 'distance_nearest_8',
 'is_street_house': 'is_street_house',
 'landSize_ratio': 'landSize_ratio',
 'landSize_ratio_with_administrative_genre': 'landSize_ratio_with_administrative_genre',
 'acreage_ratio_with_meanLandSize': 'acreage_ratio_with_meanLandSize'}


def rename_obj(obj):
    for k in rename_dict.keys():
        t = obj[k]
        del obj[k]
        obj[rename_dict[k]] = t
    return obj

def scale_data(obj):
    obj['is_street_house'] = 1 if obj['accessibility'] == 0 else 0
    obj['landSize_ratio'] = obj['landSize'] / obj['acreage']

    mean_land_size_df = mean_land_size_df_dict[obj['city']]
    obj['meanLandSize'] = mean_land_size_df[mean_land_size_df['administrative_genre'] == obj['administrative_genre']].iloc[0]['meanLandSize']

    obj['landSize_ratio_with_administrative_genre'] = obj['landSize'] / obj['meanLandSize']
    obj['acreage_ratio_with_meanLandSize'] = obj['acreage'] / obj['meanLandSize']

    del obj['meanLandSize']

    return rename_obj(obj)




