channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=24.0
- pip:
  - mlflow==2.13.2
  - catboost==1.2.5
  - cloudpickle==2.2.0
  - colorama==0.4.6
  - ipywidgets==8.1.1
  - numpy==1.23.5
  - packaging==24.0
  - pandas==2.2.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.11.4
  - uuid==1.30
  - xgboost==2.0.3
name: mlflow-env
